### PR TITLE
Added text search config option

### PR DESCRIPTION
**Pull request by siobahnv**
I think it would be neat to have the option to search by text instead of group_id for Meetup's data and here's an attempt at that.

### CODE REVIEW

**Comment by jakelandis** [comment]
@siobahnv - thanks for the contribution. Can you take a look at the failing test ? It looks like it may just be the need to do a nil check. 

```
  1) LogStash::Inputs::Meetup fetches JSON from the Meetup API
     Failure/Error: next unless rawevent['description'].downcase.include? @text.downcase
     
     NoMethodError:
       undefined method `downcase' for nil:NilClass
     # ./lib/logstash/inputs/meetup.rb:86:in `block in run'
     # ./lib/logstash/inputs/meetup.rb:83:in `block in run'
     # /home/travis/.rvm/gems/jruby-9.1.13.0/gems/stud-0.0.23/lib/stud/interval.rb:20:in `interval'
     # ./lib/logstash/inputs/meetup.rb:69:in `run'
     # ./spec/logstash/inputs/meetup_spec.rb:33:in `block in (root)'
```

**Review by jakelandis — CHANGES_REQUESTED** [review]
Changes look good.  Tested it locally and it worked great. 

One last thing... can you add the new `text` option to the documentation here: https://github.com/logstash-plugins/logstash-input-meetup/blob/master/docs/index.asciidoc

**Review by jakelandis — APPROVED** [review]

**Comment by jakelandis** [comment]
@siobahnv - thanks for the new doc, and the existing doc clean up. I will get this merged and released shortly.

**Comment by siobahnv** [comment]
Thank you @jakelandis! :)

**Comment by jakelandis** [comment]
@siobahnv - this has been released with v3.1.0 , thanks again.

**Pull request closed without merging**
